### PR TITLE
Use javascript/electron instead of ruby/phantomjs

### PR DESCRIPTION
**Pull request by joshski**
Not ready to merge, but creating the PR early for feedback.

If `bbc-a11y` switches to [Electron](http://electron.atom.io/) then...

* We can stop using PhantomJS, which only has a headless mode. With Electron, when tests fail, users can open the tool in a desktop mode, where they can use chromium dev tools to inspect the failing page in context.

* We can stop using Ruby altogether, which will simplify development and installation of the tool.

* We can package bbc-a11y and all of its dependencies as a standalone desktop application.

* Startup time will be dramatically reduced compared to Ruby, so using a11y will be a more pleasant experience in general.

### CODE REVIEW

**Comment by joshski** [comment]
@mattwynne any thoughts?

**Comment by joshski** [comment]
I've run this past a few people and my suggestion for the configuration file format is yaml, like this:

```
# a11y.yml

http://www.bbc.co.uk:
  - skip:
    - Focusable controls: anchors must have hrefs
    - Headings: exactly one main heading

http://www.bbc.co.uk/news:
  - only:
    - Tab index: elements with zero tab index must be fields
```

**Comment by joshski** [comment]
The trouble with both YAML and JSON though, is when a URL has no options such as skip/only, which should hopefully be the most common case...

In ruby we can do this:

```ruby
page "http://www.bbc.co.uk"
page "http://www.bbc.co.uk/news" do
   only "Tab index: elements with zero tab index must be fields"
end
```

...but this is awkward in any terse JSON or YAML equivalent...

In yaml you would need to add a space and a colon after each URL if it had no options:

```yaml
http://www.bbc.co.uk :
http://www.bbc.co.uk/news:
  - only:
    - Tab index: elements with zero tab index must be fields
```

...in JSON you would need to add a "null" value or an empty options object:

```json
{
   "http://www.bbc.co.uk": {},
   "http://www.bbc.co.uk/news": {
      "only": ["Tab index: elements with zero tab index must be fields"]
   }
}
```

...so I'm actually tempted to say let's stick to JavaScript:

```js
page("http://www.bbc.co.uk")
page("http://www.bbc.co.uk/news", {
  only: ["Tab index: elements with zero tab index must be fields"]
})
```

**Comment by EmmaJP** [comment]
The javascript doesn't look too bad, though more like code. I think the pros and cons between it and YAML are about the same - syntax errors with punctuation - for which the javascript may be kinder as its obvious.

If we provide comprehensive examples it should be OK for less technical users to copy and paste. And they will likely have a dev nearby who could help.

**Pull request merged**
