### PR TITLE
Test HTML against W3C validator

### PR DESCRIPTION
**Pull request by joshski**
* Validates the presence a `<!DOCTYPE>` in web pages
* When a doctype is present, submits the HTML to the W3C validator web service

### CODE REVIEW

**Comment by JamieKnightBBC** [comment]
Is the plan to implement a full validator or just a few keys checks?

**Comment by joshski** [comment]
As in, w3c validation? Yes, the plan is to plug in one of those, but this is just covering the presence of the doctype.

**Comment by joshski** [comment]
This now submits the HTML to the W3C validation web service, which is considerably slower than all other standards checks. Before I fix all the other scenarios, do we like this change? We could support it but disable it unless you opt in to it...

@JamieKnightBBC @EmmaJP what do you think?

**Comment by joshski** [comment]
(on a positive note, this has forced me to make the standards checks asynchronous, which may be useful in other future scenarios)

**Comment by freeballoon** [comment]
In general, I like the idea of validating source. Have a sneaky feeling those responsible for publishing HTML should already be doing this, yet aren't. So, if we proceed, a longer term goal may be to host a validator ourselves, e.g. in Jenkins, or as an AWS Lambda.

https://validator.w3.org/source/
=> https://validator.github.io/validator/
=> http://docs.aws.amazon.com/lambda/latest/dg/lambda-java-how-to-create-deployment-package.html

**Comment by EmmaJP** [comment]
Agree that async seems a positive step. 

There was a validator check in early bbc-a11y, but bypassing the proxy/firewall proved complex and so it was disabled by default. 

The BBC has/had an internally hosted version of the W3 validator. I don't know if that is still available. Perhaps this rule could optionally provide a way to set which validator tool is used, and how (validate a URL or validate pasted source code).

**Pull request merged**
