### PR TITLE
Pa11y dashboard integration

### PR DESCRIPTION
**Pull request by joshski**
This is mostly documentation about how to deploy a special version of pa11y dashboard and web services to heroku, (with bbc-a11y standards checks included). Here's an example of a deployed dashboard:

http://a11y-pa11y-dashboard.herokuapp.com/

### CODE REVIEW

**Comment by joshski** [comment]
The details about how to deploy to heroku can be simplified if/when these pa11y PRs are merged:

https://github.com/springernature/pa11y-dashboard/pull/101
https://github.com/springernature/pa11y-webservice/pull/14

**Comment by joshski** [comment]
Should fix https://github.com/cucumber-ltd/bbc-a11y/issues/104

**Comment by EmmaJP** [comment]
Looks great!  :-D  

It would be nice if the error message passed to the Pa11y dashboard also included a way to find/click through to where the error is.  If not a direct link, then the xpath the Ruby runner outputs... conveniently wrapped in $x("{....}") for easy copy paste into a developer console.  Chrome and Firebug both use that format.

**Comment by greenc05** [comment]
Awesome @joshski

**Comment by EmmaJP** [comment]
Having decided that setting up a Pa11y dashboard for others to use is beyond what we can currently accommodate...

It would be nice to provide some documentation on how to set-up a Pa11y dashboard with bbc-a11y available to it - ie. steps to hack the integrated HTML CodeSniffer etc.

**Comment by andymsuk** [comment]
@EmmaJP - what was the decision with this PR? Can we close it and raise a new issue or something?

**Comment by EmmaJP** [comment]
I suspect this PR would cause issues if merged. I don't know how much the master and branch have diverged since this PR was created.

However, there are aspects of the related branch that are valuable (how to integrate with Pa11y for example) and it could be worth looking into that.

**Comment by andymsuk** [comment]
Sorry, I should have clarified that I meant closing without merging.
I'd suggest closing the PR without merging, but leaving the branch there in case people want to continue at a later date.

**Pull request closed without merging**
