### PR TITLE
Update test guide

### PR DESCRIPTION
**Pull request by JamieKnightBBC**
## Summary

1. Renames the file and removes "validating" keyword
2. Adds $ convention to terminal commands.
3. Add sudo to the global install flag to avoid NPM error.

## Motivation and Context

1. Validating is confusing due to the W3C cross over. 
2. The convention of leading commands with a $ is from unix / linux going back 20 years. Makes the instructions consistent with other *nix things. 
3. NPM can't perform a global install without enhanced permissions. Sudo is required to grant NPM the requisite permissions to avoid the following error:

```
npm WARN deprecated fs-promise@2.0.1: Use mz or fs-extra^3.0 with Promise Support
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bbc/.npm/_logs/2017-11-01T15_47_51_529Z-debug.log
```

## How Has This Been Tested?

I've run through each command and tested they worked. This is the only command which failed.

## Types of changes

- [/] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by andymsuk** [comment]
@JamieKnightBBC - What are your thoughts on Josh's reply above?

**Comment by ermi-ltd** [comment]
Hi Both, I didn’t see this before today. Doh.

For the ‘’’’sudo’’’’ stuff I agree that NPM docs is better path.  A little note to say if it fails and a link would be great.

I’ll have a look at the other issue now comment on it there.

**Comment by ermi-ltd** [comment]
Gah, logged in with wrong account. This is my other account.

Jamie

**Comment by andymsuk** [comment]
@JamieKnightBBC - _bump_

**Comment by EmmaJP** [comment]
If Josh has already implemented some of these changes and others will not be implemented, can we close this pull request without merging?

**Comment by andymsuk** [comment]
@JamieKnightBBC ?

**Pull request closed without merging**
