### PR TITLE
EPR MAG update

### PR DESCRIPTION
**Pull request by EmmaJP**
## Summary 

Updates to align with new guidelines website.

## Details

These changes update URLs and align with a couple of minor title and section changes within the new guidelines website. The only potentially disruptive change is the moving and renaming of 'Managing focus' in 'Forms' section to become 'Changing focus' in 'Focus' section.

## Motivation and Context

Issues #295  and #294 are relevant and both connected to the BBC accessibility guidelines moving to a new website.

## How Has This Been Tested?

No tests have been run yet. This is a draft pull request to enable that to happen.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I've added tests for my code
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by EmmaJP** [comment]
Thanks for the additional changes @llouisetaylor looks like I missed a few. Looks like the CI checks are still failing. I'm wondering if related changes are needed in the checks... thought detail implies it can't load electron (CI stuff is definitely not my area of expertise).

**Comment by llouisetaylor** [comment]
The above changes fixed 5/6 of the failing tests. The remaining test I had been struggling to understand:
```
Error: Failed to answer "Are actions triggered when appropriate for the type of user interaction?" with "Yes"
       Text in answer frame:
       Does focus or context automatically change during user input?

       No (or not applicable)Yes
```

**Comment by EmmaJP** [comment]
I wonder if that's one of the non-automated tests mis-matching with something that has been changed. It is odd.

**Comment by EmmaJP** [comment]
@andymsuk or @jroebu14 would one of you be able to help @llouisetaylor with the final failing test of this PR?

**Pull request closed without merging**
